Squash merge from 534 commits

diff --git a/appimage_creator/create_appimage.sh.in b/appimage_creator/create_appimage.sh.in
--- a/appimage_creator/create_appimage.sh.in
+++ b/appimage_creator/create_appimage.sh.in
@@ -1,40 +1,38 @@
 #!/bin/bash
+set -euo pipefail
 
 QT_VERSION=6.8.3
 export PATH=/home/work/fs_Qt/$QT_VERSION/gcc_64/bin/:$PATH
-export LD_LIBRARY_PATH=/home/work/fs_Qt/$QT_VERSION/gcc_64/lib/:$LD_LIBRARY_PATH
+export LD_LIBRARY_PATH=/home/work/fs_Qt/$QT_VERSION/gcc_64/lib/:${LD_LIBRARY_PATH:-}
 export LD_LIBRARY_PATH=/home/work/fs_DABstar/appimage_creator/stublibs/:$LD_LIBRARY_PATH
 
 DST=~/DABstarAppImage
+LINUXDEPLOYQT="linuxdeployqt-continuous-x86_64.AppImage"
 
-mkdir -p $DST
+mkdir -p "$DST"
 
-mkdir -p $DST/appdir/usr/bin
-mkdir -p $DST/appdir/usr/lib
-mkdir -p $DST/appdir/usr/share/applications
-mkdir -p $DST/appdir/usr/share/icons/hicolor/256x256/apps/
-#mkdir -p $DST/appdir/usr/share/icons/hicolor/scalable/apps/
+mkdir -p "$DST/appdir/usr/bin"
+mkdir -p "$DST/appdir/usr/lib"
+mkdir -p "$DST/appdir/usr/share/applications"
+mkdir -p "$DST/appdir/usr/share/icons/hicolor/256x256/apps/"
+#mkdir -p "$DST/appdir/usr/share/icons/hicolor/scalable/apps/"
 
-cp dabstar.desktop              $DST/appdir/usr/share/applications
-#cp ../res/logo/dabstar.png     $DST/appdir/
-cp ../res/logo/dabstar.png      $DST/appdir/usr/share/icons/hicolor/256x256/apps/
-#cp ../res/logo/dabstar.svg     $DST/appdir/
-#cp ../res/logo/dabstar.svg     $DST/appdir/usr/share/icons/hicolor/scalable/apps/
-cp /usr/local/lib/librtlsdr.so  $DST/appdir/usr/lib/
+cp dabstar.desktop              "$DST/appdir/usr/share/applications"
+#cp ../res/logo/dabstar.png     "$DST/appdir/"
+cp ../res/logo/dabstar.png      "$DST/appdir/usr/share/icons/hicolor/256x256/apps/"
+#cp ../res/logo/dabstar.svg     "$DST/appdir/"
+#cp ../res/logo/dabstar.svg     "$DST/appdir/usr/share/icons/hicolor/scalable/apps/"
+cp /usr/local/lib/librtlsdr.so  "$DST/appdir/usr/lib/"
 
-cd $DST || exit
+cd "$DST"
 
-# from here the build folder with the build has to be exist in the folder $DST
+# from here the build folder with the build has to exist in the folder $DST
 cp build/dabstar appdir/usr/bin/
 
-wget -q --show-progress -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
-chmod a+x linuxdeployqt*.AppImage
+wget -q --show-progress -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/$LINUXDEPLOYQT"
+chmod a+x "$LINUXDEPLOYQT"
 
-# shellcheck disable=SC2211
-./linuxdeployqt*.AppImage ./appdir/usr/share/applications/* -appimage -no-translations
-
-# if all worked fine add the version number to the generated filename
-if [ $? -eq 0 ]; then
+if ./"$LINUXDEPLOYQT" ./appdir/usr/share/applications/* -appimage -no-translations; then
   echo "linuxdeployqt runs successfully"
   APP_NAME="@PROJECT_NAME@"
   APP_VERS="@PROJECT_VERSION@"
@@ -43,5 +41,6 @@ if [ $? -eq 0 ]; then
   FN_DST="${APP_NAME}-${APP_VERS}-${APP_ARCH}.AppImage"
   mv -f -v "$FN_SRC" "$FN_DST"
 else
-  echo "linuxdeployqt failed with $?"
+  echo "linuxdeployqt failed"
+  exit 1
 fi
